# Generated by Django 6.0.7 on 2026-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_counterparty_remove_transaction_supplier_or_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='internal_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Внутренний код'),
        ),
        migrations.AddField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(default='шт', max_length=10, verbose_name='Ед. изм. (вес/объем)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Значение (вес/объем)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена продажи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул (SKU)'),
        ),
    ]
