# Generated by Django 6.0.7 on 2026-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_price_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Артикул'),
        ),
    ]
