# Generated by Django 6.0.7 on 2026-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure_unit',
            field=models.CharField(choices=[('мл', 'мл (миллилитры)'), ('г', 'г (граммы)')], default='мл', max_length=10, verbose_name='Ед. изм. (вес/объем)'),
        ),
    ]
