# Generated by Django 6.0.7 on 2026-08-04 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_code', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Счетчик кодов товаров',
                'verbose_name_plural': 'Счетчики кодов товаров',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_code',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Внутренний код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='inventory.counterparty', verbose_name='Поставщик'),
        ),
    ]
