# Generated by Django 6.0.7 on 2026-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productcodesequence_alter_product_internal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название компании'),
        ),
    ]
