# Generated by Django 6.0.7 on 2026-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_transaction_receipt_transaction_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
