# Generated by Django 6.0.7 on 2026-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_receiptitem_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='name',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ИНН'),
        ),
    ]
