# Generated by Django 6.0.7 on 2026-08-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_counterparty_name_counterparty_company_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='counterparty',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'customer')), fields=('type', 'first_name', 'last_name'), name='unique_customer_name'),
        ),
    ]
