# Generated by Django 6.0.7 on 2026-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_counterparty_is_deleted_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, unique=True, verbose_name='Тип документа')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Последний номер')),
            ],
            options={
                'verbose_name': 'Счетчик документов',
                'verbose_name_plural': 'Счетчики документов',
            },
        ),
    ]
