# Generated by Django 6.0.7 on 2026-09-28 15:01

from django.db import migrations

from django.db import migrations
from django.db.models import Max

def sync_document_sequences(apps, schema_editor):
    # Получаем исторические версии моделей (это важно для миграций)
    Sale = apps.get_model('inventory', 'Sale')
    Receipt = apps.get_model('inventory', 'Receipt')
    DocumentSequence = apps.get_model('inventory', 'DocumentSequence')

    # Синхронизируем продажи
    max_sale = Sale.objects.aggregate(Max('number'))['number__max'] or 0
    seq_sale, _ = DocumentSequence.objects.get_or_create(document_type='sale')
    seq_sale.last_number = max_sale
    seq_sale.save()

    # Синхронизируем приходы
    max_receipt = Receipt.objects.aggregate(Max('number'))['number__max'] or 0
    seq_receipt, _ = DocumentSequence.objects.get_or_create(document_type='receipt')
    seq_receipt.last_number = max_receipt
    seq_receipt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_documentsequence'),
    ]

    operations = [
        migrations.RunPython(sync_document_sequences),
    ]
